In [ ]:
Import NumPy as np

In [1]:
import numpy as np

In [ ]:
##Create an array of 10 zeros

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
##Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
##Create an array of 10 fives

In [6]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
#Create an array of the integers from 10 to 50

In [9]:
range(10,50)

range(10, 50)

In [11]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#Create an array of all the even integers from 10 to 50

In [13]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
#Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
a1=np.arange(0,9)

In [18]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
a1.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#Create a 3x3 identity matrix

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Use NumPy to generate a random number between 0 and 1

In [22]:
np.random.rand()

0.8344621384034462

In [ ]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution¶

In [23]:
np.random.randn(25)

array([-0.48583527,  0.07110513, -1.15565586,  0.74216716,  0.58464197,
       -0.30357505, -1.19744914,  1.65291186,  1.00566221,  1.58875214,
       -0.07626178, -0.67217369,  0.39601646, -0.10554648,  0.42746044,
        0.49198587,  0.53640263, -0.45748843, -1.21012384,  0.56029865,
       -1.53000303, -0.98389689, -0.93476709, -2.20122699, -1.9071164 ])

In [ ]:
#Create the following matrix

In [24]:
a2=np.arange(1,101)

In [25]:
a2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
a2.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [28]:
a2.reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
#Create an array of 20 linearly spaced points between 0 and 1:

In [29]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [32]:
arr=np.arange(1,26)

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [34]:
arr=np.arange(1,26).reshape(5,5)

In [35]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
Q:array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [36]:
arr[2: ,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
Q:20

In [37]:
arr[3:4,4:]

array([[20]])

In [ ]:
Q:array([[ 2],
       [ 7],
       [12]])

In [38]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
Q:array([21, 22, 23, 24, 25])

In [40]:
arr[4:]

array([[21, 22, 23, 24, 25]])

In [42]:
arr[4:5,0:5]

array([[21, 22, 23, 24, 25]])

In [ ]:
Q:array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
arr[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
arr[3:5,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [45]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
arr.sum()

325

In [ ]:
Q:Get the standard deviation of the values in mat

In [47]:
arr.std()

7.211102550927978

In [ ]:
Q:Get the sum of all the rows in mat

In [57]:
arr.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [55]:

arr.sum(axis=0)

array([55, 60, 65, 70, 75])